info:
  contact: {}
paths:
  /:
    get:
      description: Get details of all orders
      responses:
        "200": {}
      summary: just the landing page
  /api/v1/user:
    post:
      consumes:
      - application/json
      description: Allows login to the application by generating a JWT
      produces:
      - text/plain; charset=utf-8
      responses:
        "200":
          description: Bearer Token
      summary: Login to the application, generates a JWT
swagger: "2.0"
